### ISSUE TITLE
URDF support

### ISSUE THREAD

**Issue by shbang91** [tasts-robots/pink#7]
Hello,

I've noticed that pink only supports URDF in the robot_description repo. Is there any way I could use my custom URDF?

Thank you,
Seung Hyeon

**Comment by stephane-caron** [comment]
Absolutely. Pink works directly on Pinocchio robots, so you can call Pinocchio's ``BuildFromURDF`` to load your custom URDF.

I just pushed a convenience [`load_urdf`](https://github.com/tasts-robots/pink/blob/95ccaf355826fc8cdf4a8bb94fc169ebb6fa5312/pink/utils.py#L47) function that adds some doc around this:

```python
def load_urdf(urdf_path: str, package_dirs: List[str] = [], free_flyer: bool = True) -> pin.RobotWrapper:
    """
    Load the URDF of a robot description.

    Args:
        urdf_path: Path to the URDF file.
        package_dirs: List of directories Pinocchio can use as guesses to expand relative and ``package://`` paths in the URDF.
        free_flyer: Add a free flyer (a.k.a. floating base) as the first joint of the kinematic chain.
    """
    return pin.RobotWrapper.BuildFromURDF(
        filename=urdf_path,
        package_dirs=package_dirs,
        root_joint=pin.JointModelFreeFlyer() if free_flyer else None,
    )
```

**Comment by stephane-caron** [comment]
There is now a small [`load_custom_urdf.py`](https://github.com/tasts-robots/pink/blob/db8296fab997c375bdfe031c468528c3a18ef684/examples/load_custom_urdf.py) example showing how to load a custom double-pendulum URDF.

Hoping this helps :slightly_smiling_face:

**Comment by shbang91** [comment]
Thank you so much for your great effort on this!
